import { Injectable } from '@angular/core';
import { CoreValue } from './core-value';

@Injectable({
  providedIn: 'root'
})
export class ValuesManagerService {
  private userVals: CoreValue[];

  constructor() { 
    this.userVals = valueArray.map((value, index) => ({
      id: index,
      value: value,
      trashed: false
    }));
  }
  
  getNumVals() : Number {
    return this.userVals.length;
  }
}

const valueArray = [
  "Abundance",
  "Acceptance",
  "Accountability",
  "Accuracy",
  "Achievement",
  "Adaptability",
  "Adventure",
  "Affection",
  "Alignment",
  "Alone Time",
  "Altruism",
  "Anti-Racism",
  "Appreciation",
  "Artistry",
  "Autonomy",
  "Authenticity",
  "Awareness",
  "Balance",
  "Beauty",
  "Belonging",
  "Bliss",
  "Boldness",
  "Bravery",
  "Calmness",
  "Caring",
  "Change",
  "Change the World",
  "Charisma",
  "Charity",
  "Clarity",
  "Cleanliness",
  "Clear Communication",
  "Cleverness",
  "Community",
  "Compassion",
  "Confidence",
  "Consciousness",
  "Consistency",
  "Contentment",
  "Contribution",
  "Cooperation",
  "Courage",
  "Creativity",
  "Credibility",
  "Curiosity",
  "Decisiveness",
  "Dedication",
  "Deep Connections",
  "Dependability",
  "Dignity",
  "Efficiency",
  "Empathy",
  "Encouragement",
  "Enthusiasm",
  "Entrepreneurship",
  "Environmental Protection",
  "Equity",
  "Equality",
  "Excellence",
  "Expansion",
  "Experimentation",
  "Exploration",
  "Fairness",
  "Faith",
  "Fame",
  "Family ",
  "Fidelity",
  "Financial Security",
  "Finesse",
  "Forgiveness",
  "Freedom",
  "Friendliness",
  "Friendship",
  "Fun",
  "Generosity",
  "Gentleness",
  "Going with the Flow",
  "Goodness",
  "Grace ",
  "Gracefulness",
  "Gratitude",
  "Happiness",
  "Harmony",
  "Health",
  "Honesty",
  "Honor",
  "Hope",
  "Humility",
  "Humor",
  "Imagination",
  "Independence",
  "Influence",
  "Ingenuity",
  "Inspiration",
  "Inspirational",
  "Initiative",
  "Innovation",
  "Insightfulness",
  "Integrity",
  "Intimacy",
  "Intuition",
  "Job Security",
  "Joy",
  "Justice",
  "Kindness",
  "Knowledge",
  "Laughter",
  "Lawfulness",
  "Leadership",
  "Learning",
  "Legacy",
  "Loyalty",
  "Making a difference",
  "Mentorship",
  "Modesty",
  "Mutual Support",
  "Nature",
  "Natural Living",
  "Non-Conformity",
  "Non-Violence",
  "Open-Mindedness",
  "Openness",
  "Optimism",
  "Order",
  "Organization",
  "Originality",
  "Passion",
  "Patience",
  "Peace",
  "Peace of Mind",
  "Perseverance",
  "Persistence",
  "Personal Development",
  "Personal Expression",
  "Personal Fulfillment",
  "Planning",
  "Playfulness",
  "Positive Attitude",
  "Positive Impact",
  "Power",
  "Presence",
  "Pride",
  "Problem-Solving",
  "Professionalism",
  "Profit",
  "Promise-keeping",
  "Prosperity",
  "Protecting Others",
  "Quality",
  "Reciprocity",
  "Recognition",
  "Reliability",
  "Resourcefulness",
  "Respect",
  "Responsibility",
  "Restraint",
  "Righteousness",
  "Risk-taking",
  "Romance",
  "Self-Discipline",
  "Self-Expression",
  "Self-Love",
  "Self-Motivation",
  "Self-Preservation",
  "Self-Respect",
  "Selflessness",
  "Service  ",
  "Service to Others",
  "Simplicity",
  "Sincerity",
  "Social Justice",
  "Spirituality",
  "Spontaneity",
  "Sportsmanship",
  "Stability",
  "Stewardship",
  "Strength",
  "Success",
  "Sustainability",
  "Sweetness",
  "Teamwork",
  "Thoughtfulness",
  "Thrift",
  "Tidiness",
  "Timeliness",
  "Tolerance",
  "Tradition",
  "Transparency",
  "Travel",
  "Truth",
  "Trust",
  "Trust Your Gut",
  "Understanding",
  "Uniqueness",
  "Vivaciousness",
  "Vision",
  "Vulnerability",
  "Warmth",
  "Wealth",
  "Well-being",
  "Wellness",
  "Wholeheartedness",
  "Wisdom",
  "Wit",
]
